version: '3'

services:
  mysql-mq:
    build: .
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql-mq.mysql.local
      - MYSQL_USER=root
      - MYSQL_PASS=root
    command: ["./docker/wait-for-it.sh", "-h", "mysql-mq.mysql.local", "-p", "3306", "--", "npm", "test"]
    depends_on:
      - mysql
    container_name: mysql-mq.core.local

  mysql:
    image: mysql:latest
    ports:
      - 3380:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mp_test
    container_name: mysql-mq.mysql.local
